### PR TITLE
Add recommended folder structure to readme

### PR DESCRIPTION
**Pull request by ranmerc**
Please review and suggest if any changes required.

### CODE REVIEW

**Comment by MoeenKhalil** [comment]
I think there is no need of having a <slot>, it looks verbose and complex, apart from that everything looks great.

**Comment by ranmerc** [comment]
Sorry but having a what?

**Comment by MoeenKhalil** [comment]
"Slot" i wanted to mention, my bad!

**Comment by ranmerc** [comment]
The question papers change based on the slot. But I agree that it should be skipped if only one slot's papers are available.

**Comment by MoeenKhalil** [comment]
Irrespective of the slots, I think at the end of the day it is just a different set of questions for the same subject, so having a 'slot' doesn't make it any better I guess. having just folders like 'ETH' and 'ELA' would be sufficient to place theory and lab-related material in the respective fields.

**Pull request merged**
